export const CHANNEL_TYPES = [
  'bluesky',
  'calendar',
  'custom',
  'deca',
  'discord',
  'ens',
  'email',
  'farcaster',
  'friendtech',
  'gallery',
  'github',
  'instagram',
  'lens',
  'linkedin',
  'linkedin-company',
  'linktree',
  'medium',
  'mirror',
  'nftd',
  'opensea',
  'paragraph',
  'phone',
  'portrait',
  'readcv',
  'reddit',
  'researchhub',
  'signal',
  'soundcloud',
  'spotify',
  'steam',
  'telegram',
  'tenfold',
  'tiktok',
  'threads',
  'twitch',
  'twitter',
  'wallet',
  'whatsapp',
  'xmtp',
] as const;

export const EXCLUDED_CHANNEL_TYPES = new Set<ChannelType>([
  'linkedin-company',
  'xmtp',
  'tenfold',
]);

export const EDITABLE_CHANNEL_TYPES = CHANNEL_TYPES.filter(
  (contactType) => !EXCLUDED_CHANNEL_TYPES.has(contactType),
);

type ChannelType = (typeof CHANNEL_TYPES)[number];

export const CHANNEL_TYPE_PREFIXES: Partial<Record<ChannelType, string>> = {
  bluesky: 'bsky.app/profile/',
  deca: 'deca.art/',
  farcaster: 'warpcast.com/',
  friendtech: 'friend.tech/rooms/',
  gallery: 'gallery.so/',
  github: 'github.com/',
  instagram: 'instagram.com/',
  lens: 'hey.xyz/u/',
  linkedin: 'linkedin.com/in/',
  'linkedin-company': 'linkedin.com/company/',
  linktree: 'linktr.ee/',
  medium: 'medium.com/',
  mirror: 'mirror.xyz/',
  nftd: 'nf.td/',
  opensea: 'opensea.io/',
  paragraph: 'paragraph.xyz/',
  portrait: 'portrait.so/',
  readcv: 'read.cv/',
  reddit: 'reddit.com/u/',
  researchhub: 'researchhub.com/user/',
  signal: 'signal.me/#p/',
  soundcloud: 'soundcloud.com/',
  spotify: 'open.spotify.com/user/',
  steam: 'steamcommunity.com/id/',
  telegram: 't.me/',
  tenfold: 'tenfold.xyz/profile/',
  tiktok: 'tiktok.com/',
  threads: 'threads.net/',
  twitch: 'twitch.tv/',
  twitter: 'twitter.com/',
  whatsapp: 'wa.me/',
};

export const CHANNEL_TYPE_PLACEHOLDERS: Record<ChannelType, string> = {
  bluesky: 'Username or handle',
  calendar: 'Full URL calendar link',
  custom: 'Full URL custom link',
  deca: 'Username or handle',
  discord: 'Username or handle',
  ens: 'Ens name',
  email: 'Full email address',
  farcaster: 'Username or handle',
  friendtech: 'Friendtech address',
  gallery: 'Username or handle',
  github: 'Username or handle',
  instagram: 'Username or handle',
  lens: 'Username or handle',
  linkedin: 'Username after linkedin.com/in/',
  'linkedin-company': 'Username after linkedin.com/company/',
  linktree: 'Username or handle',
  medium: 'Username or handle',
  mirror: 'Username or handle',
  nftd: 'Username or handle',
  opensea: 'Username or handle',
  paragraph: 'Username or handle',
  phone: 'Phone number',
  portrait: 'Username or handle',
  readcv: 'Username or handle',
  reddit: 'Username or handle',
  researchhub: 'Username or handle',
  signal: 'Phone number +1234567890',
  soundcloud: 'Username or handle',
  spotify: 'Username or handle',
  steam: 'Username or handle',
  telegram: 'Username or handle',
  tenfold: 'Username or handle',
  tiktok: 'Username or handle',
  threads: 'Username or handle',
  twitch: 'Username or handle',
  twitter: 'Username or handle',
  wallet: 'Web3 address',
  whatsapp: 'Phone number +1234567890',
  xmtp: 'Web3 address',
};

export const PRIVATE_CHANNEL_TYPES = new Set<ChannelType>([
  'email',
  'phone',
  'custom',
  'calendar',
  'signal',
  'telegram',
  'whatsapp',
]);

export const PUBLIC_CHANNEL_TYPES = new Set<ChannelType>(
  CHANNEL_TYPES.filter(
    (channelType) => !PRIVATE_CHANNEL_TYPES.has(channelType),
  ),
);

export const BG_COLORS: Partial<Record<ChannelType, string>> = {
  bluesky: 'blue.200',
  deca: '#171717',
  discord: '#7289DA',
  ens: '#3888FF',
  farcaster: '#432B8C',
  friendtech: '#FFFFFF',
  github: 'gray.800',
  instagram: 'orange.500',
  lens: '#FE4869',
  linkedin: '#2D64BC',
  'linkedin-company': '#2D64BC',
  linktree: '#43E660',
  mirror: '#007AFF',
  nftd: '#D4FFE3',
  opensea: '#2E8DEE',
  paragraph: 'gray.800',
  phone: 'green.500',
  portrait: '#000000',
  readcv: 'FFFFFF',
  researchhub: '#39719D',
  reddit: '#FF4500',
  signal: '#3872E8',
  soundcloud: '#FF7700',
  spotify: '#1ED760',
  steam: '#00ADEE',
  telegram: 'linear-gradient(180deg, #38ACE8 0%, #299DD5 100%)',
  tenfold: '#FFFFFF',
  tiktok: '#69C9D0',
  threads: 'black',
  twitch: '#6441A5',
  twitter: '#1DA1F2',
  whatsapp: '#3BDA57',
  xmtp: '#FC4F37',
};
